import type { Metadata } from "next";
import { Orbitron,Inter,Irish_Grover } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/public/navbar";
import Footer from "@/components/public/footer";

const OrbitronFont = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
  weight: ["400", "700"],
});

const InterFont = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "700"],
});

const IrishGroverFont = Irish_Grover({
  subsets: ["latin"],
  variable: "--font-irish-grover",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OrbitronFont.variable} ${InterFont.variable} ${IrishGroverFont.variable} antialiased`}
      >
        <div className='fixed top-0 left-0 right-0 z-50'>
          <Navbar/>
        </div>
        {children}
        <div>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
